// Team name -> ISO country code for flagcdn.com. Broad WC set so live TxLINE
// names resolve too. Unknown names return null (caller hides the flag).
const CODES: Record<string, string> = {
  argentina: 'ar',
  australia: 'au',
  austria: 'at',
  belgium: 'be',
  'bosnia and herzegovina': 'ba',
  brazil: 'br',
  cameroon: 'cm',
  canada: 'ca',
  chile: 'cl',
  colombia: 'co',
  croatia: 'hr',
  denmark: 'dk',
  'dr congo': 'cd',
  ecuador: 'ec',
  egypt: 'eg',
  england: 'gb-eng',
  france: 'fr',
  germany: 'de',
  ghana: 'gh',
  iran: 'ir',
  italy: 'it',
  japan: 'jp',
  mexico: 'mx',
  morocco: 'ma',
  netherlands: 'nl',
  nigeria: 'ng',
  norway: 'no',
  paraguay: 'py',
  peru: 'pe',
  poland: 'pl',
  portugal: 'pt',
  qatar: 'qa',
  'saudi arabia': 'sa',
  scotland: 'gb-sct',
  senegal: 'sn',
  serbia: 'rs',
  'south korea': 'kr',
  korea: 'kr',
  spain: 'es',
  sweden: 'se',
  switzerland: 'ch',
  tunisia: 'tn',
  turkey: 'tr',
  'united states': 'us',
  usa: 'us',
  uruguay: 'uy',
  wales: 'gb-wls',
  algeria: 'dz',
  'cape verde': 'cv',
  'cabo verde': 'cv',
  jordan: 'jo',
  uzbekistan: 'uz',
  'new zealand': 'nz',
  'ivory coast': 'ci',
  "cote d'ivoire": 'ci',
  'south africa': 'za',
  panama: 'pa',
  curacao: 'cw',
  haiti: 'ht',
  honduras: 'hn',
  'costa rica': 'cr',
  jamaica: 'jm',
  greece: 'gr',
  ukraine: 'ua',
  slovakia: 'sk',
  slovenia: 'si',
  czechia: 'cz',
  'czech republic': 'cz',
  romania: 'ro',
  hungary: 'hu',
  finland: 'fi',
  iceland: 'is',
  ireland: 'ie',
  'republic of ireland': 'ie',
  'northern ireland': 'gb-nir',
  albania: 'al',
  'north macedonia': 'mk',
  kosovo: 'xk',
  georgia: 'ge',
  venezuela: 've',
  bolivia: 'bo',
  china: 'cn',
  'china pr': 'cn',
  iraq: 'iq',
  israel: 'il',
  thailand: 'th',
  vietnam: 'vn',
  'united arab emirates': 'ae',
  uae: 'ae',
  oman: 'om',
  bahrain: 'bh',
  kuwait: 'kw',
  lebanon: 'lb',
  mali: 'ml',
  'burkina faso': 'bf',
  guinea: 'gn',
  gabon: 'ga',
  zambia: 'zm',
  angola: 'ao',
  mozambique: 'mz',
  namibia: 'na',
  libya: 'ly',
  sudan: 'sd',
  tanzania: 'tz',
  kenya: 'ke',
  uganda: 'ug',
  'trinidad and tobago': 'tt',
  'el salvador': 'sv',
  guatemala: 'gt',
  india: 'in',
  indonesia: 'id',
  'korea republic': 'kr',
  'ir iran': 'ir',
  turkiye: 'tr',
}

export function flagCode(name: string): string | null {
  // strip accents (Türkiye, Curaçao, Côte d'Ivoire…) and periods before lookup
  const key = name
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\./g, '')
  return CODES[key] ?? null
}

export function flagUrl(name: string, size: 'w20' | 'w40' | 'w80' | 'w160' = 'w40'): string | null {
  const code = flagCode(name)
  return code ? `https://flagcdn.com/${size}/${code}.png` : null
}

// Where to look a scorer up (current club, profile). Transfermarkt quick search
// always resolves, even for demo names.
export function playerSearchUrl(name: string): string {
  return `https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=${encodeURIComponent(name)}`
}
